seed: 42
device: cuda
wandb:
  enable: false
  project: "lerobot-pi0-eval"
  entity: "your_wandb_entity"
  mode: "disabled"
policy:
  dtype: "bfloat16" # we use flash-attn which requires bfloat16, during training this is handled by mixed precision, during inference we set the full model to bfloat16

dataset_path: "/home/irl-admin/chekpoints/4th_March_folding"  #"/home/irl-admin/gianluca/eval_pull_2026-01-27_17-35-18/datasets/lerobot/move_block" #"/home/irl-admin/gianluca/lerobot_dataset_stats/pepper" 
task_instruction: "Pick up the bell pepper and place it in the bowl." #"Fold the scarf on the table" # #"Move the block to the center, then move it back to its initial position." #"Pick up the bell pepper and place it in the bowl." # "Touch first the blue, then the red and finally the green block."#"Pick up the bell pepper and place it in the bowl." #

checkpoint_path: "/home/irl-admin/chekpoints/4th_March_folding/pretrained_model"
